# Generated by Django 3.0.4 on 2020-04-03 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200403_2156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacancy',
            old_name='company_id',
            new_name='company',
        ),
    ]
