# Generated by Django 3.0.4 on 2020-04-03 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_vacancy_salary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='company_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='company_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='vacancy',
            old_name='vacancy_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='vacancy',
            old_name='vacancy_name',
            new_name='name',
        ),
    ]
