# Generated by Django 3.0.4 on 2020-04-03 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacancy',
            old_name='company_name',
            new_name='company_id',
        ),
    ]
